// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using lookbook_dotnet_api.data;

#nullable disable

namespace lookbook_dotnet_api.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20240910124745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lookbook_dotnet_api.models.Lookbook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Lookbooks");
                });

            modelBuilder.Entity("lookbook_dotnet_api.models.LookbookProduto", b =>
                {
                    b.Property<int>("LookbookId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("LookbookId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("LookbookProduto");
                });

            modelBuilder.Entity("lookbook_dotnet_api.models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<double>("Preco")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("lookbook_dotnet_api.models.LookbookProduto", b =>
                {
                    b.HasOne("lookbook_dotnet_api.models.Lookbook", "Lookbook")
                        .WithMany("LookbookProdutos")
                        .HasForeignKey("LookbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lookbook_dotnet_api.models.Produto", "Produto")
                        .WithMany("LookbookProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lookbook");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("lookbook_dotnet_api.models.Lookbook", b =>
                {
                    b.Navigation("LookbookProdutos");
                });

            modelBuilder.Entity("lookbook_dotnet_api.models.Produto", b =>
                {
                    b.Navigation("LookbookProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
